name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test-report:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with Gradle
        run: ./gradlew test

      - name: Copy Gradle Test Reports
        if: always()
        run: |
          chmod +x .github/workflows/filter_and_copy.sh
          ./.github/workflows/filter_and_copy.sh

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/workflows/reports
          publish_branch: main


