name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test-report:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with Gradle
        run: ./gradlew test

      - name: Copy Gradle Test Reports
        if: always()
        run: |
          chmod +x .github/workflows/filter_and_copy.sh
          ./.github/workflows/filter_and_copy.sh

      - name: Stash or discard local changes
        run: |
          git stash || echo "No changes to stash"

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Remove old reports in gh-pages
        run: |
          rm -rf * 

      - name: Copy reports from main to gh-pages
        run: |
          cp -r .github/workflows/reports/* .

      - name: Commit and push changes to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git commit -m "Update test reports" || echo "No changes to commit"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/workflows/reports
          publish_branch: gh-pages

      - name: Clean up temp directory
        run: rm -rf temp-reports

